### ISSUE TITLE
Use Case diagrams in Excel

### ISSUE THREAD

**Issue by lalacreu** [smart-grid-use-cases/excel2xml-input#10]
It should be possible to display use case diagrams of Excel defined use cases as it is done for XML defined use cases.

**Comment by lalacreu** [comment]
to test the functionality.

**Comment by lalacreu** [comment]
Markus, add some comments on the documentation. @m-mirz

**Comment by m-mirz** [comment]
I have added a sentence saying that the image files should be in the same folder as the Excel file and the image name should be indicated in the URI Excel sheet field. I guess that a more detailed explanation will be provided here: https://github.com/smart-grid-use-cases/excel2xml-input/issues/11

**Comment by m-mirz** [comment]
Images are not correctly displayed for Excel use cases.
