### ISSUE TITLE
ebalance use cases 5, 8, 9

### ISSUE THREAD

**Issue by m-mirz** [smart-grid-use-cases/excel2xml-input#23]
- [UC8](https://github.com/smart-grid-use-cases/excel2xml-input/tree/master/excel-use-cases/EBALANCE-PLUS/UC8) and [UC9](https://github.com/smart-grid-use-cases/excel2xml-input/tree/master/excel-use-cases/EBALANCE-PLUS/UC9) cannot be converted due to an error
- formatting in [UC5](https://github.com/smart-grid-use-cases/excel2xml-input/tree/master/excel-use-cases/EBALANCE-PLUS/UC5) is not correct starting from [Section 4.2](https://smart-grid-use-cases.github.io/docs/usecases/ebalance-plus/uc5/#42-steps--scenarios)

**Comment by MiloszKrysik** [comment]
Hello, do you have any updates about it? @m-mirz

**Comment by richardmarston** [comment]
There are date cells with spaces inside them. I will make excel2xml handle this situation correctly.

**Comment by richardmarston** [comment]
Solved by pull request:
https://github.com/smart-grid-use-cases/excel2xml/pull/8
